### ISSUE TITLE
Define supported environments

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#26]
For GUI we need to define what browsers (and version of that) on what OS that we support or at least test on.

**Comment by pamasse** [comment]
Hi @matsduf,

I've done some test with different tools like [browserstack](www.browserstack.com). With this kind of tool we can automate the test of the gui very easily (because the gui is very simple).

I ask for a free plan (https://www.browserstack.com/open-source) for zonemaster GUI. But, to accept the free plan, they would like their logo on the zonemaster gui readme page. 

What do you think about this?

**Comment by sandoche2k** [comment]
Could be closed when the PR https://github.com/zonemaster/zonemaster/pull/756 is closed? @pamasse

**Comment by matsduf** [comment]
Defined in zonemaster/zonemaster.
